CREATE TABLE IF NOT EXISTS contacts (
  id INT AUTO_INCREMENT PRIMARY KEY,
  wa_id VARCHAR(64) UNIQUE,
  name VARCHAR(255) NOT NULL DEFAULT '',
  phone VARCHAR(32),
  status VARCHAR(32) NOT NULL DEFAULT 'prospect',
  notes TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_contacts_phone (phone)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS conversations (
  chat_id VARCHAR(64) PRIMARY KEY,
  last_read_ts BIGINT NOT NULL DEFAULT 0,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS messages (
  id INT AUTO_INCREMENT PRIMARY KEY,
  session_id VARCHAR(64),
  wa_message_id VARCHAR(128),
  chat_id VARCHAR(64) NOT NULL,
  direction ENUM('incoming','outgoing') NOT NULL,
  from_me TINYINT(1) NOT NULL DEFAULT 0,
  body TEXT,
  type VARCHAR(32) NOT NULL DEFAULT 'text',
  ts BIGINT NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'sent',
  idempotency_key VARCHAR(128) UNIQUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_messages_chat (chat_id, ts),
  INDEX idx_messages_wa (wa_message_id)
) ENGINE=InnoDB;
